apiVersion: v1 
kind: Pod 
metadata:
  name: pod-configmap # Nombre del pod de ejemplo 
spec:
  containers:
    - name: nginx 
      image: mysql:8.0 # Imagen empleada para el configmap
      envFrom:
        - configMapRef:
            name: configmap-mysql # Referencia al ConfigMap