apiVersion: apps/v1 #DaemonSet
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch #La función de este ejemplo, es la de ejecutar la imagen Docker fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector: #Es el selector de pod y funciona igual que el selector de un job
    matchLabels:
      name: fluentd-elasticsearch
  template: #Es una plantilla Pod, es decir, tiene el mismo esquema que un Pod, excepto por el hecho de que está anidado
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: fluentd-elasticsearch
        image: gcr.io/fluentd-elasticsearch/fluentd:v2.5.1
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

