apiVersion: v1 #Servicio headless
kind: Service
metadata:
  name: nginx #Se utiliza nginx para publicar las direcciones IP de los Pods en el Stateful web
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1 #StatefulSet
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 5 #El stateful, llamado web, tiene un spec que indica que se lanzarán 5 réplicas del contenedor nginx en Pods únicos.
  selector:
    matchLabels:
      app: nginx # tiene que coincidir con .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: nginx # tiene que coincidir con .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates: #volumeClaimTemplate proporcino almacenamiento estable por medio de PersistentVolumes provisionados por un provisionador de tipo PersistentVolume
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


